# ______________________________________________________________________________________
### AuthService
POST {{baseUrl}}/auth/sso
Content-type: Application/json

{
    "email": "rafael.perez@broxel.com",
    "password": "12345"
}

# __________________________________________________________________________________________________________
### Users Endpoints
Get {{baseUrl}}/users/ HTTP/1.1
####
GET {{baseUrl}}/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMiLCJlbWFpbCI6Im1vY2FycmFuemEwOEBnbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6Ik3Dk05JQ0EgRVNQRVJBTlpBIENBUlJBTlpBIFZBTERFWiIsImp0aSI6ImJjMGM5OWVlLTBhYzctNDMxMy05ZWQxLTNmNTY2NDgyYjQ0ZCIsIm5iZiI6MTc2Mjk1NjMwOCwiZXhwIjoxNzYyOTU3MjA4LCJpYXQiOjE3NjI5NTYzMDgsImlzcyI6ImJyb3hjaGFpbiIsImF1ZCI6ImJyb3hjaGFpbiJ9.H4lf6neWEGJwwbj-KlVtMRDIrEoaTZF589zFCRDPBa8
####
Post {{baseUrl}}/users
Content-type: Application/Json

{
    "name": "RAFAEL PEREZ CASTILLO",
    "rfc": "XAXX010101000",
    "correo": "rafael.perez@broxel.com",
    "telefono": "5574357032",
    "curp": "PECR930809HMSF05"
}

####
PUT {{baseUrl}}/users/11
Content-type: Application/Json

{
    "curp": "PECR930809HMSF051"
}

####
DELETE {{baseUrl}}/users/2
# ________________________________________________________________________________________________________________________________________________________________
####  PrecioEndpoint
GET {{baseUrl}}/precios

###
GET {{baseUrl}}/precios/166

###
POST {{baseUrl}}/precios
Content-type: Application/Json

{
    "FechaPrecio": "2020-01-01",
    "PrecioMxn": 0.0223631
}

### 
PUT {{baseUrl}}/precios/166
Content-type: Application/Json

{
    "FechaPrecio": "2020-01-01",
    "PrecioMxn": 23.89
}

###
DELETE {{baseUrl}}/precios/166

# __________________________________________________________________________
####  Flujo Endpoint
GET {{baseUrl}}/flujos

###
GET {{baseUrl}}/flujos/62

###
POST {{baseUrl}}/flujos
Content-type: Application/Json

{
    "DiaMovimiento": "2020-01-01",
    "Importe": 12.89,
    "Comision": 12.89,
    "InversionistaId": 1
}

### 
PUT {{baseUrl}}/flujos/62
Content-type: Application/Json

{
    "FechaPrecio": "2020-01-01",
    "PrecioMxn": 23.89,
    "InversionistaId": 1
}

###
DELETE {{baseUrl}}/flujos/2

# _____________________________________________________________________________
# Servicios especiales  Usar estos 

###
POST {{baseUrl}}/precios/saldos
Authorization: Bearer sPbYNYtnN+lfZzGfG5orn+xc+WbPQgCsDxBZwclISzdgkuVr4h9XZIAwGtvZJvYbR38wTW8KJFxO06lgKb/wrNLcVaLwYbvfIr+urirvpy9UXu7AeOAwN+fXo4Bz1wx7zdFJFTp6swVzsTmhfRYiyzBj/YxCj5dhu93lFp2CYD+c1yBVXjaH8ibugBOVgg8tiWAF9uH0q1UCH2BaahdqHKmYjwOxtrh93s6uvOwRZ+2zvUBKmrJquJB7mQbT7P1IAZ3NCsL/XHRJnmzb4B/XNqePiYxfgpACTSFncAEbelaKo5n6VVXsn5ujSP1Pt5tfmrbYbJR28aD+LJ0JpQAZ3DUaqhmFOAOABNeTwMN+HlV/b6Mmjl+bxfeCQJrCiCrH2ebNeZtyoB9ILSe9sftubHqxd9wInJr4iP74NF0Udyr0fSpqoC5cMc+B73GLHZIt/iH5tz9QIElGzaAV9vpZk2hyP+Bw+F8e449laeZyTs1QtcHkjlXtOVJyOZGsuSn8wE6K7NUQWHHM6zVeOyrF+ts79+nody+TNbBxd4qHbnk=

{
    "tipo": 1
}

###
POST {{baseUrl}}/precios/saldos
Content-type: Application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzIiwiZW1haWwiOiJtb2NhcnJhbnphMDhAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNw5NOSUNBIEVTUEVSQU5aQSBDQVJSQU5aQSBWQUxERVoiLCJqdGkiOiIwNzAzZjczYi1kZGQyLTQ1M2YtYjJhNS1lOWFkZDQxMDE3MGUiLCJuYmYiOjE3NjM3NDUyNDMsImV4cCI6MTc2Mzc0NzA0MywiaWF0IjoxNzYzNzQ1MjQzLCJpc3MiOiJicm94Y2hhaW4iLCJhdWQiOiJicm94Y2hhaW4ifQ.tWHbeR7qwAX7NtSj_CoATssJmskxku0tW4aVAC6Fvvw

{
    "tipo": 0
}
###
GET {{baseUrl}}/precios/valoresMercado
Content-type: Application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzIiwiZW1haWwiOiJtb2NhcnJhbnphMDhAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNw5NOSUNBIEVTUEVSQU5aQSBDQVJSQU5aQSBWQUxERVoiLCJqdGkiOiIwNzAzZjczYi1kZGQyLTQ1M2YtYjJhNS1lOWFkZDQxMDE3MGUiLCJuYmYiOjE3NjM3NDUyNDMsImV4cCI6MTc2Mzc0NzA0MywiaWF0IjoxNzYzNzQ1MjQzLCJpc3MiOiJicm94Y2hhaW4iLCJhdWQiOiJicm94Y2hhaW4ifQ.tWHbeR7qwAX7NtSj_CoATssJmskxku0tW4aVAC6Fvvw

###
GET {{baseUrl}}/precios
Content-type: Application/json
Authorization: Bearer FDdW4ETtxft4KA9EeJv3+z8tTkAKk7pq8OBL2YutSWMfcgQrijdUqRHfX+dUU3i20UauErDRhWt2BQq2GMKszvJ66aEFqg0KPZCkbTJuQNTv6sm3ILU/od9HALLwmmN5nurzjP8A38TOBWcf2vs9Oew0hw9dBbAAc7OXlRwTF1ZgW29xqLnO5oFqCTN1rWZrGiSN0PbNO74y4e9u8YhxgAoznaL6ANhq2aT4VCzl8xnCiCw4d5FPzNAhCO9GZNe4Tn+gz3ksMSbBKtfJSZ7LGQQXsY4BXD8hR6OwdbWKHo/pSGkG8bMuzKdSbEbjob89G7Q0GLTbUuaGzxR4Hhs7Z4sVgWj0TRVTJVR5RKgWYUXmTq/ERfXghw9j/3KPa7eUGAYnS68gvJs/y+xYk8YfUJ6tH8qaPC1ygwmzqNZRgG52VkI0PXT17ItSjdXqptzKoYY8VAxnD1cetLAC0eGcWL+zTd6DE7AdTyGlOgRaeqRdF9LVVrzw86gzi5wk4dV01jMvI71kZRpCk5mkIwOT7ze5m+qRNi7cg4kmL8PK+x4=

###
GET {{baseUrl}}/precios/flujoPrecios
Content-type: Application/json
Authorization: Bearer HTCCVLEK9HqDH1rX4wlSG79rJKrLz141WU2juoDaIUYhJ2DLk3OjppBcS/U6YhaDmHnGfIWG5rjpE5/qnuXekec8mU4wjbnlTMSLAnShG7jCdbpykfupKez0XRdiPkwFUwpClYCkNuXCsCjstmz0yF1QK40O2CJtESLwv8gccjb/NP7zlbHU/NtbZkBQrCJrXxCWMpvvZLzoMzVXPUN4Egl29zQfp1AHas0WS9Q6+bsjRvRarICwyIyr72qF9++E0ObHMivoHkGYeiPxDujvuzfIwjZEkEwJAvBt9iop15OvMOS3tpL+M82SvPIuz8EZXOLanbhC0gVRD3U032tpxLQA2tn/4bm1tLDfdSUK/fHVMIxGHz/C/a3a6utcwVAq35zmXZ6qOr1uQekkeql1Si1cPXaK6bXxpazYgcXbO0gT5BVvH1emNNa87ihfoz5n2Io6zh/+JhdQuFFBVB2BdUutzXYr5IvDj5XWj+542TF8KS6qzv4MxGZQA2HsjuhSc4LVmCI0zhYdgzo2De8EkL8M+3xO818/rQRDBE98TIE=



# ______________________________________________________________________________________
### AuthService
POST {{baseUrl}}/auth/sso
Content-type: Application/json

{
    "email": "mocarranza08@gmail.com",
    "password": "12345"
}
###
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "RefreshToken": "I+4Zcrrc41UmWi7CSMP4XxMHaAbvoCWF75XiHoivCzdtFX0wQH8EYH+ETI8sjvYvBiE8lIBsujSGaSZCZ4ymWoLvxkoXqxulJBD22zLElvf/ZpavGB/Pmeq4/TxSo4AJznp/VJsRZ9aRojhRlCC6Uv8qL94ETUr83ji8iePlbT5mPqfmISpwkOPRc20PrlLb2NlSsWawqntH2LER7EJpog8f0elWzuhtbkhq5nFaB97ppC3HzdLkP7gmLBLJ7DgcdHuBzTugubG4tef28t8DGITD3mk8kwzRlAm9nrRg8ukcdQkD/30lcLuEEGZikG+4echRBK+VdXViVANXade8uTB1vkRtVFe84I10PNPlWkl2tF3l68I2lROPm0jPccEUFUt5LqSXjH5EXqxssX9NnGobOEDMGYWVALwPfnQgfxoQFwc2wgL/tfEsUnQhVoBG"
}

### 
POST {{baseUrl}}/auth/validate
Content-Type: application/json


{
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExIiwiZW1haWwiOiJyYWZhZWwucGVyZXpAYnJveGVsLmNvbSIsInVuaXF1ZV9uYW1lIjoiUkFGQUVMIFBFUkVaIENBU1RJTExPIiwianRpIjoiNGEzNjIzZmMtY2QwZi00Mzk4LTk0OWUtYWJlZWNmZmNkZjQwIiwibmJmIjoxNzYyNDQzNjM2LCJleHAiOjE3NjI0NTA4MzYsImlhdCI6MTc2MjQ0MzYzNiwiaXNzIjoiYnJveGNoYWluIiwiYXVkIjoiYnJveGNoYWluIn0.fHgmpyqztqShtEYydWPh0M4v8Uz9M2neAOdiVhSwh8o"
}

### 
POST {{baseUrl}}/auth/revoke
Content-Type: application/json

{
    "RefreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzIiwidG9rZW5UeXBlIjoicmVmcmVzaCIsImp0aSI6IjMyM2M2NGViLTVmMGYtNGVjMi04ZDEwLWNkODYyMWU0MTNlMyIsIm5iZiI6MTc2MzQ5MDE5NiwiZXhwIjoxNzY0MDk0OTk2LCJpYXQiOjE3NjM0OTAxOTYsImlzcyI6ImJyb3hjaGFpbiIsImF1ZCI6ImJyb3hjaGFpbiJ9.URtEYtjeikcAsO8hieCy53h7rRA9A31cuzpO_dOSXUE"
}

### Logout
POST {{baseUrl}}/auth/logout
Content-type: Application/json

{
    "RefreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzIiwidG9rZW5UeXBlIjoicmVmcmVzaCIsImp0aSI6ImU3NzNhYTQzLTBlY2QtNDZjNS05YmJlLTU5Y2NkMmQ3ZDcyOSIsIm5iZiI6MTc2MzQ5MzgzNywiZXhwIjoxNzY0MDk4NjM3LCJpYXQiOjE3NjM0OTM4MzcsImlzcyI6ImJyb3hjaGFpbiIsImF1ZCI6ImJyb3hjaGFpbiJ9.GhsTqoRUN3geQ2C-A6xP5KJA6opfS9LcRMbw6mRhjxA"
}