# ______________________________________________________________________________________
### AuthService
POST {{baseUrl}}/auth/sso
Content-type: Application/json

{
    "email": "rafael.perez@broxel.com",
    "password": "12345"
}

# __________________________________________________________________________________________________________
### Users Endpoints
Get {{baseUrl}}/users/ HTTP/1.1
####
GET {{baseUrl}}/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMiLCJlbWFpbCI6Im1vY2FycmFuemEwOEBnbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6Ik3Dk05JQ0EgRVNQRVJBTlpBIENBUlJBTlpBIFZBTERFWiIsImp0aSI6ImJjMGM5OWVlLTBhYzctNDMxMy05ZWQxLTNmNTY2NDgyYjQ0ZCIsIm5iZiI6MTc2Mjk1NjMwOCwiZXhwIjoxNzYyOTU3MjA4LCJpYXQiOjE3NjI5NTYzMDgsImlzcyI6ImJyb3hjaGFpbiIsImF1ZCI6ImJyb3hjaGFpbiJ9.H4lf6neWEGJwwbj-KlVtMRDIrEoaTZF589zFCRDPBa8
####
Post {{baseUrl}}/users
Content-type: Application/Json

{
    "name": "RAFAEL PEREZ CASTILLO",
    "rfc": "XAXX010101000",
    "correo": "rafael.perez@broxel.com",
    "telefono": "5574357032",
    "curp": "PECR930809HMSF05"
}

####
PUT {{baseUrl}}/users/11
Content-type: Application/Json

{
    "curp": "PECR930809HMSF051"
}

####
DELETE {{baseUrl}}/users/2
# ________________________________________________________________________________________________________________________________________________________________
####  PrecioEndpoint
GET {{baseUrl}}/precios

###
GET {{baseUrl}}/precios/166

###
POST {{baseUrl}}/precios
Content-type: Application/Json

{
    "FechaPrecio": "2020-01-01",
    "PrecioMxn": 0.0223631
}

### 
PUT {{baseUrl}}/precios/166
Content-type: Application/Json

{
    "FechaPrecio": "2020-01-01",
    "PrecioMxn": 23.89
}

###
DELETE {{baseUrl}}/precios/166

# __________________________________________________________________________
####  Flujo Endpoint
GET {{baseUrl}}/flujos

###
GET {{baseUrl}}/flujos/62

###
POST {{baseUrl}}/flujos
Content-type: Application/Json

{
    "DiaMovimiento": "2020-01-01",
    "Importe": 12.89,
    "Comision": 12.89,
    "InversionistaId": 1
}

### 
PUT {{baseUrl}}/flujos/62
Content-type: Application/Json

{
    "FechaPrecio": "2020-01-01",
    "PrecioMxn": 23.89,
    "InversionistaId": 1
}

###
DELETE {{baseUrl}}/flujos/2

# _____________________________________________________________________________
# Servicios especiales  Usar estos 

###
POST {{baseUrl}}/precios/saldos
Content-type: Application/json
Authorization: Bearer HW6JYz37lB0QjfIsmh3N3ca2XOL9TelLXXNhHHbquhykokEotlslPq+sHlJTA2Tzghpq+i6GS7gNHtqy2MLKtzVHOzXPfnmmUBJ6gp8PQ8kKPNIVCTAkKgXNuKei8wGp3hUWXQAD0qeQUx48fW5Rwo4Ax+bD4xBGU9FJ+chya5glwRyBNFTjS068B0NgQ24mvHq5ztatQB81AGmTaSy+9LAGUQ20dqt8eloOeRg3SOBU2EN18oKZCxkScyI17/O+cLTlTmP4AYgsyeX5s3KFmL380DtG5ORlkzznYHnqZdLmXK0W4SZRvdCSV/Ss7W8JlhctERuKy23SxdgfP1a1ShM51ubXJzgF2Ji+Ujv9IFUIZAEQhvu+3jCzZ5hl1dX3beyPboa+j++GuH+isE5SVcl8/w9hhNurF9O+wCYk9drMaBcPYUuKUTPRGx6LIXOh/qByYQVAmtYURbzbNU42u2RSZKtdKT07UoxwCxNrze9egDcqQc94aAMcCrkw1bwf

{
    "tipo": 1
}

###
POST {{baseUrl}}/precios/saldos
Content-type: Application/json
Authorization: Bearer HW6JYz37lB0QjfIsmh3N3ca2XOL9TelLXXNhHHbquhykokEotlslPq+sHlJTA2Tzghpq+i6GS7gNHtqy2MLKtzVHOzXPfnmmUBJ6gp8PQ8kKPNIVCTAkKgXNuKei8wGp3hUWXQAD0qeQUx48fW5Rwo4Ax+bD4xBGU9FJ+chya5glwRyBNFTjS068B0NgQ24mvHq5ztatQB81AGmTaSy+9LAGUQ20dqt8eloOeRg3SOBU2EN18oKZCxkScyI17/O+cLTlTmP4AYgsyeX5s3KFmL380DtG5ORlkzznYHnqZdLmXK0W4SZRvdCSV/Ss7W8JlhctERuKy23SxdgfP1a1ShM51ubXJzgF2Ji+Ujv9IFUIZAEQhvu+3jCzZ5hl1dX3beyPboa+j++GuH+isE5SVcl8/w9hhNurF9O+wCYk9drMaBcPYUuKUTPRGx6LIXOh/qByYQVAmtYURbzbNU42u2RSZKtdKT07UoxwCxNrze9egDcqQc94aAMcCrkw1bwf

{
    "tipo": 0
}
###
GET {{baseUrl}}/precios/valoresMercado
Content-type: Application/json
Authorization: Bearer HW6JYz37lB0QjfIsmh3N3ca2XOL9TelLXXNhHHbquhykokEotlslPq+sHlJTA2Tzghpq+i6GS7gNHtqy2MLKtzVHOzXPfnmmUBJ6gp8PQ8kKPNIVCTAkKgXNuKei8wGp3hUWXQAD0qeQUx48fW5Rwo4Ax+bD4xBGU9FJ+chya5glwRyBNFTjS068B0NgQ24mvHq5ztatQB81AGmTaSy+9LAGUQ20dqt8eloOeRg3SOBU2EN18oKZCxkScyI17/O+cLTlTmP4AYgsyeX5s3KFmL380DtG5ORlkzznYHnqZdLmXK0W4SZRvdCSV/Ss7W8JlhctERuKy23SxdgfP1a1ShM51ubXJzgF2Ji+Ujv9IFUIZAEQhvu+3jCzZ5hl1dX3beyPboa+j++GuH+isE5SVcl8/w9hhNurF9O+wCYk9drMaBcPYUuKUTPRGx6LIXOh/qByYQVAmtYURbzbNU42u2RSZKtdKT07UoxwCxNrze9egDcqQc94aAMcCrkw1bwf

###
GET {{baseUrl}}/precios
Content-type: Application/json
Authorization: Bearer HW6JYz37lB0QjfIsmh3N3ca2XOL9TelLXXNhHHbquhykokEotlslPq+sHlJTA2Tzghpq+i6GS7gNHtqy2MLKtzVHOzXPfnmmUBJ6gp8PQ8kKPNIVCTAkKgXNuKei8wGp3hUWXQAD0qeQUx48fW5Rwo4Ax+bD4xBGU9FJ+chya5glwRyBNFTjS068B0NgQ24mvHq5ztatQB81AGmTaSy+9LAGUQ20dqt8eloOeRg3SOBU2EN18oKZCxkScyI17/O+cLTlTmP4AYgsyeX5s3KFmL380DtG5ORlkzznYHnqZdLmXK0W4SZRvdCSV/Ss7W8JlhctERuKy23SxdgfP1a1ShM51ubXJzgF2Ji+Ujv9IFUIZAEQhvu+3jCzZ5hl1dX3beyPboa+j++GuH+isE5SVcl8/w9hhNurF9O+wCYk9drMaBcPYUuKUTPRGx6LIXOh/qByYQVAmtYURbzbNU42u2RSZKtdKT07UoxwCxNrze9egDcqQc94aAMcCrkw1bwf

###
GET {{baseUrl}}/precios/flujoPrecios
Content-type: Application/json
Authorization: Bearer HW6JYz37lB0QjfIsmh3N3ca2XOL9TelLXXNhHHbquhykokEotlslPq+sHlJTA2Tzghpq+i6GS7gNHtqy2MLKtzVHOzXPfnmmUBJ6gp8PQ8kKPNIVCTAkKgXNuKei8wGp3hUWXQAD0qeQUx48fW5Rwo4Ax+bD4xBGU9FJ+chya5glwRyBNFTjS068B0NgQ24mvHq5ztatQB81AGmTaSy+9LAGUQ20dqt8eloOeRg3SOBU2EN18oKZCxkScyI17/O+cLTlTmP4AYgsyeX5s3KFmL380DtG5ORlkzznYHnqZdLmXK0W4SZRvdCSV/Ss7W8JlhctERuKy23SxdgfP1a1ShM51ubXJzgF2Ji+Ujv9IFUIZAEQhvu+3jCzZ5hl1dX3beyPboa+j++GuH+isE5SVcl8/w9hhNurF9O+wCYk9drMaBcPYUuKUTPRGx6LIXOh/qByYQVAmtYURbzbNU42u2RSZKtdKT07UoxwCxNrze9egDcqQc94aAMcCrkw1bwf



# ______________________________________________________________________________________
### AuthService
POST {{baseUrl}}/auth/sso
Content-type: Application/json

{
    "email": "Admin@broxchain.com",
    "password": "12345"
}
###
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "RefreshToken": "I+4Zcrrc41UmWi7CSMP4XxMHaAbvoCWF75XiHoivCzdtFX0wQH8EYH+ETI8sjvYvBiE8lIBsujSGaSZCZ4ymWoLvxkoXqxulJBD22zLElvf/ZpavGB/Pmeq4/TxSo4AJznp/VJsRZ9aRojhRlCC6Uv8qL94ETUr83ji8iePlbT5mPqfmISpwkOPRc20PrlLb2NlSsWawqntH2LER7EJpog8f0elWzuhtbkhq5nFaB97ppC3HzdLkP7gmLBLJ7DgcdHuBzTugubG4tef28t8DGITD3mk8kwzRlAm9nrRg8ukcdQkD/30lcLuEEGZikG+4echRBK+VdXViVANXade8uTB1vkRtVFe84I10PNPlWkl2tF3l68I2lROPm0jPccEUFUt5LqSXjH5EXqxssX9NnGobOEDMGYWVALwPfnQgfxoQFwc2wgL/tfEsUnQhVoBG"
}

### 
POST {{baseUrl}}/auth/validate
Content-Type: application/json


{
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExIiwiZW1haWwiOiJyYWZhZWwucGVyZXpAYnJveGVsLmNvbSIsInVuaXF1ZV9uYW1lIjoiUkFGQUVMIFBFUkVaIENBU1RJTExPIiwianRpIjoiNGEzNjIzZmMtY2QwZi00Mzk4LTk0OWUtYWJlZWNmZmNkZjQwIiwibmJmIjoxNzYyNDQzNjM2LCJleHAiOjE3NjI0NTA4MzYsImlhdCI6MTc2MjQ0MzYzNiwiaXNzIjoiYnJveGNoYWluIiwiYXVkIjoiYnJveGNoYWluIn0.fHgmpyqztqShtEYydWPh0M4v8Uz9M2neAOdiVhSwh8o"
}

### 
POST {{baseUrl}}/auth/revoke
Content-Type: application/json

{
    "RefreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzIiwidG9rZW5UeXBlIjoicmVmcmVzaCIsImp0aSI6IjMyM2M2NGViLTVmMGYtNGVjMi04ZDEwLWNkODYyMWU0MTNlMyIsIm5iZiI6MTc2MzQ5MDE5NiwiZXhwIjoxNzY0MDk0OTk2LCJpYXQiOjE3NjM0OTAxOTYsImlzcyI6ImJyb3hjaGFpbiIsImF1ZCI6ImJyb3hjaGFpbiJ9.URtEYtjeikcAsO8hieCy53h7rRA9A31cuzpO_dOSXUE"
}

### Logout
POST {{baseUrl}}/auth/logout
Content-type: Application/json

{
    "RefreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzIiwidG9rZW5UeXBlIjoicmVmcmVzaCIsImp0aSI6ImU3NzNhYTQzLTBlY2QtNDZjNS05YmJlLTU5Y2NkMmQ3ZDcyOSIsIm5iZiI6MTc2MzQ5MzgzNywiZXhwIjoxNzY0MDk4NjM3LCJpYXQiOjE3NjM0OTM4MzcsImlzcyI6ImJyb3hjaGFpbiIsImF1ZCI6ImJyb3hjaGFpbiJ9.GhsTqoRUN3geQ2C-A6xP5KJA6opfS9LcRMbw6mRhjxA"
}