// <auto-generated />
using System;
using FondoInversion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FondoInversion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113162824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("FondoInversion.Models.Flujo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Comision")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DiaMovimiento")
                        .HasColumnType("DATE")
                        .HasColumnName("dia_movimiento");

                    b.Property<double>("Importe")
                        .HasColumnType("REAL")
                        .HasColumnName("importe");

                    b.Property<int>("InversionistaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inversionista_id");

                    b.HasKey("Id");

                    b.HasIndex("InversionistaId");

                    b.ToTable("flujo", (string)null);
                });

            modelBuilder.Entity("FondoInversion.Models.Precio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaPrecio")
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_precio");

                    b.Property<double>("PrecioMxn")
                        .HasColumnType("REAL")
                        .HasColumnName("precio_mxn");

                    b.HasKey("Id");

                    b.ToTable("precio", (string)null);
                });

            modelBuilder.Entity("FondoInversion.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correo");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rfc");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("FondoInversion.Models.Flujo", b =>
                {
                    b.HasOne("FondoInversion.Models.User", "Inversionista")
                        .WithMany("Flujos")
                        .HasForeignKey("InversionistaId")
                        .IsRequired();

                    b.Navigation("Inversionista");
                });

            modelBuilder.Entity("FondoInversion.Models.User", b =>
                {
                    b.Navigation("Flujos");
                });
#pragma warning restore 612, 618
        }
    }
}
