// <auto-generated />
using System;
using FondoInversion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FondoInversion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229191444_InitialCreateSQLServer")]
    partial class InitialCreateSQLServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FondoInversion.Models.accesoUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("intentos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ultimoIntento")
                        .HasColumnType("datetime");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__accesoUs__3213E83FA656F1CD");

                    b.HasIndex("userID");

                    b.ToTable("accesoUser");
                });

            modelBuilder.Entity("FondoInversion.Models.adminUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("rol")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("id")
                        .HasName("PK__adminUse__3213E83F2761EE0B");

                    b.ToTable("adminUsers");
                });

            modelBuilder.Entity("FondoInversion.Models.eventLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("message")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__eventLog__3213E83F329D075A");

                    b.ToTable("eventLog");
                });

            modelBuilder.Entity("FondoInversion.Models.flujo", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<double>("comision")
                        .HasColumnType("float");

                    b.Property<DateOnly>("dia_movimiento")
                        .HasColumnType("date");

                    b.Property<double>("importe")
                        .HasColumnType("float");

                    b.Property<int>("inversionista_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__flujo__3213E83F399E913D");

                    b.HasIndex("inversionista_id");

                    b.ToTable("flujo");
                });

            modelBuilder.Entity("FondoInversion.Models.precio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("fecha_precio")
                        .HasColumnType("date");

                    b.Property<double>("precio_mxn")
                        .HasColumnType("float");

                    b.HasKey("id")
                        .HasName("PK__precio__3213E83F7DEC59F5");

                    b.HasIndex(new[] { "fecha_precio" }, "UQ__precio__E5CD410C546B8B96")
                        .IsUnique();

                    b.ToTable("precio");
                });

            modelBuilder.Entity("FondoInversion.Models.token", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("activo")
                        .HasColumnType("int");

                    b.Property<DateTime>("expiracion")
                        .HasColumnType("datetime");

                    b.Property<string>("refreshToken")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__tokens__3213E83FFD91BCFC");

                    b.HasIndex("userID");

                    b.ToTable("tokens");
                });

            modelBuilder.Entity("FondoInversion.Models.transactionLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("requestBody")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__transact__3213E83FA47BDB6D");

                    b.HasIndex("userID");

                    b.ToTable("transactionLogs");
                });

            modelBuilder.Entity("FondoInversion.Models.user", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("curp")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("rfc")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("id")
                        .HasName("PK__user__3213E83F99A70B0B");

                    b.HasIndex(new[] { "correo" }, "UQ__user__2A586E0BD88A8B2F")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("FondoInversion.Models.accesoUser", b =>
                {
                    b.HasOne("FondoInversion.Models.user", "user")
                        .WithMany("accesoUsers")
                        .HasForeignKey("userID")
                        .IsRequired()
                        .HasConstraintName("FK__accesoUse__userI__59FA5E80");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FondoInversion.Models.flujo", b =>
                {
                    b.HasOne("FondoInversion.Models.user", "inversionista")
                        .WithMany("flujos")
                        .HasForeignKey("inversionista_id")
                        .IsRequired()
                        .HasConstraintName("FK__flujo__inversion__4CA06362");

                    b.Navigation("inversionista");
                });

            modelBuilder.Entity("FondoInversion.Models.token", b =>
                {
                    b.HasOne("FondoInversion.Models.user", "user")
                        .WithMany("tokens")
                        .HasForeignKey("userID")
                        .IsRequired()
                        .HasConstraintName("FK__tokens__userID__72C60C4A");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FondoInversion.Models.transactionLog", b =>
                {
                    b.HasOne("FondoInversion.Models.user", "user")
                        .WithMany("transactionLogs")
                        .HasForeignKey("userID")
                        .IsRequired()
                        .HasConstraintName("FK__transacti__userI__5535A963");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FondoInversion.Models.user", b =>
                {
                    b.Navigation("accesoUsers");

                    b.Navigation("flujos");

                    b.Navigation("tokens");

                    b.Navigation("transactionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
